services:
  telegrambot:
    image: telegrambot
    build:
      context: ./telegrambot
    container_name: telegrambot
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - TB_TOKEN=${TB_TOKEN}
      - TB_AUTORIZADOS=${TB_AUTORIZADOS}
