services:
  telegrambot:
    image: telegrambot
    build:
      context: ./telegrambot
    container_name: telegrambot
    environment:
      - SERVIDOR=${SERVIDOR}
      - TB_TOKEN=${TB_TOKEN}
      - TB_AUTORIZADOS=${TB_AUTORIZADOS}
      - TZ=America/Argentina/Buenos_Aires 
      - MQTT_PASS=${MQTT_PASS}
      - MQTT_USR=${MQTT_USR}
      - PUERTO_MQTTS=${PUERTO_MQTTS}
      - TOPICO=${TOPICO}
